# 一、 ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维的数组 arr    注意列表和数组并不完全一样，只是相似
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

5
arr的维度： 0


In [3]:
arr = np.array([1,2,3])  # 创建1维的数组 arr
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

[1 2 3]
arr的维度： 1


In [4]:
arr = np.array([[1,2,3],[4,5,6]])  # 创建2维的数组 arr
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [5]:
arr = np.array([1,'hello'])  #不同的数据类型会被强制转换相同
print(arr)

['1' 'hello']


## 2.ndarray的属性

In [6]:
arr = np.array(1)
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

1
数组的形状： ()
arr的维度： 0
元素的个数： 1
元素的数据类型： int32
元素的转置 1


In [7]:
arr = np.array([1,2.5,3])
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
arr的维度： 1
元素的个数： 3
元素的数据类型： float64
元素的转置 [1.  2.5 3. ]


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
arr的维度： 2
元素的个数： 6
元素的数据类型： int32
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [9]:
#基础的创建方法
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [10]:
#基础的创建方法,与上面划等号
list1 = [1,2,3]
arr = np.array(list1,dtype=np.float64) #可以强制转化元素类型
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [11]:
# copu
arr1 = np.copy(arr) #内容一样，但是是两个数组
print(arr1)

[1. 2. 3.]


In [12]:
# 预定义形状
# 全0 全1 未初始化
# 全0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [13]:
arr = np.zeros((2,3),dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [14]:
# 全1
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 未初始化，值不确定
arr = np.empty((4,3))
print(arr)

[[1.31491532e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.04082753e-047]
 [5.89571563e-091 2.90003500e-057 2.36842381e+179]
 [1.35055174e+161 3.99910963e+252 2.44749283e-056]]


In [16]:
# full
arr = np.full((2,3),2025)
print(arr)

[[2025 2025 2025]
 [2025 2025 2025]]


In [17]:
arr1 = np.zeros_like(arr) #会覆盖之前的2025
print(arr1)

[[0 0 0]
 [0 0 0]]


In [18]:
# 等差数列 2,4,6,8
arr = np.arange(1,10,1) #start,end,step,[ , )
print(arr)

[1 2 3 4 5 6 7 8 9]


In [19]:
# 等间隔数列
arr = np.linspace(1,10,5) #start,end,几份
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
arr = np.linspace(0,100,5,dtype=int) #start,end,几份
print(arr)

[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2)  #start,end,几份，以2为底
print(arr)   #2的0次方是1，2次方是4，4次方是16

[ 1.  4. 16.]


In [22]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3,dtype = int)  #3是形状
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
arr = np.eye(3,4,dtype = int)  #3,4是形状
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [24]:
# 对角矩阵:主对角线上的数字非0，其余为0
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [25]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）   均匀分布指的是概率相等
arr = np.random.rand(2,3)
print(arr)

[[0.43051824 0.44674287 0.72270205]
 [0.8632845  0.50335642 0.74539202]]


In [26]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3)) #3 到6
print(arr)

[[5.43494199 5.13574446 5.1510719 ]
 [4.22972887 3.0187061  3.02159824]]


In [27]:
# 生成指定范围区间的随机整数
arr = np.random.randint(2,30,(2,3)) #2到30，(  ]
print(arr)

[[27  6  3]
 [ 7 20 17]]


In [28]:
#生成随机数列 （正态分布） 
arr = np.random.randn(2,3) 
print(arr)

[[-0.72499335 -1.25948673 -1.46560511]
 [ 1.24300954  0.60401801  1.05458657]]


## 4 索引与切片

In [29]:
arr = np.random.randint(1,100,20)
print(arr)

[21 36 47 75 41 36 21 68 53 43 91  5 72 13  9 32 87  5 57  2]


In [30]:
print(arr[:]) #获取全部数据
print(arr[2:5]) #获取2到4的元素  [  )
print(arr[(arr>10) & (arr<60)]) #布尔索引，就是条件
print(arr[slice(2,5)])  # start,end,step  [    )

[21 36 47 75 41 36 21 68 53 43 91  5 72 13  9 32 87  5 57  2]
[47 75 41]
[21 36 47 41 36 21 53 43 13 32 57]
[47 75 41]


In [31]:
# 二维数组索引和切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[17 86 83 63 67 42 97 85]
 [90 66 31  8  3 70 72 41]
 [21 13 75 84 94 24 75 22]
 [66 94 36 79 43 47 49 55]]


In [32]:
print(arr[1,3])   # 索引
print(arr[ 1,2:5])  # 1指的是第“1”行    2；5是2到5
print(arr[arr>50])  # 会变成一维数组
print(arr[2][ arr[2] > 50])    #第“2”行 大于50

8
[31  8  3]
[86 83 63 67 97 85 90 66 70 72 75 84 94 75 66 94 79 55]
[75 84 94 75]


## 5 ndarray运算

In [33]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)    #包括其余  - * / **

[5 7 9]


In [34]:
c = [1,2,3]
d = [4,5,6]
print(c+d)   #这里是列表和数组的差距,列表只能拼接

[1, 2, 3, 4, 5, 6]


In [35]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3) # 依旧演示,各个位置都加3   其余算数同理

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# 广播机制: 1 获取形状 2 是否可以广播         例如 1 * 2 和 1*3不行
# 同意维度 : 相同
a = np.array([1,2,3])  #  1 * 3
b = np.array([[4],[5],[6]]) # 3 * 1
print(a+b)
#      a
#    1 2 3
#    1 2 3
#    1 2 3
#      b
#    4 4 4
#    5 5 5
#    6 6 6 

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a*b)  # 这是数组的乘
print(a @ b) #这是矩阵的乘

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 二 numpy中的数学函数

## 1.基本数学函数

In [47]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [52]:
# 计算指数  默认以e为底  e^x
print(np.exp(1))
print(np.exp(0))

2.718281828459045
1.0


In [58]:
# 计算自然对数   默认e为底 ln x
print(np.log(2.71))

0.9969486348916096


In [66]:
# 计算正弦余弦
print(np.sin(np.pi/2))
print(np.cos(0))

1.0
1.0


In [67]:
# 计算绝对值
arr = np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [68]:
# 计算a的b次幂
print(np.power(arr,3))

[ -1   1   8 -27]


In [70]:
# 四舍五入
print(np.round([3.2,4.5,8.51,9.6]))

[ 3.  4.  9. 10.]


In [73]:
# 向上取整和向下取整
arr = np.array([3.2,4.5,8.51,9.6])
print(np.ceil(arr))
print(np.floor(arr))

[ 4.  5.  9. 10.]
[3. 4. 8. 9.]


In [74]:
# 检测缺失值NAN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

# 2.统计函数 
  求和，计算平均值，计算中位数，标准差，方差，查找最大值，最小值
  计算分为数，累计和，累计差

In [76]:
arr = np.random.randint(1,20,8)
print(arr)

[19 11 17  7 17  7 19  9]


In [79]:
#求和
print(np.sum([1,2,3]))

6


In [80]:
# 平均值
print(np.mean((arr)))

13.25


In [82]:
# 中位数
print(np.median([1,2,3,4]))
print(np.median([1,2,4]))

2.5
2.0


In [85]:
# 计算标准差，方差  
print(np.var([1,2,3]))
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [86]:
# 最大值最小值

In [88]:
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[19 11 17  7 17  7 19  9]
19 0
7 3


In [93]:
# 分为数，中位数  
print(np.median([1,2,3]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,50))  # 就是百分之五十

2.0
[44 47 64 67]
55.5
55.5


In [96]:
# 累计和，累计积
arr = np.array([1,2,3])
print(np.sum(arr)) # 求和
print(np.cumsum(arr)) # 累计和
print(np.cumprod(arr)) # 累计积

6
[1 3 6]
[1 2 6]
