# 一、 ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维的数组 arr    注意列表和数组并不完全一样，只是相似
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

5
arr的维度： 0


In [3]:
arr = np.array([1,2,3])  # 创建1维的数组 arr
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

[1 2 3]
arr的维度： 1


In [4]:
arr = np.array([[1,2,3],[4,5,6]])  # 创建2维的数组 arr
print(arr)
print("arr的维度：",arr.ndim) # 数组的维度

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [5]:
arr = np.array([1,'hello'])  #不同的数据类型会被强制转换相同
print(arr)

['1' 'hello']


## 2.ndarray的属性

In [6]:
arr = np.array(1)
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

1
数组的形状： ()
arr的维度： 0
元素的个数： 1
元素的数据类型： int32
元素的转置 1


In [7]:
arr = np.array([1,2.5,3])
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
arr的维度： 1
元素的个数： 3
元素的数据类型： float64
元素的转置 [1.  2.5 3. ]


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("数组的形状：",arr.shape)
print("arr的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的数据类型：",arr.dtype)
print("元素的转置",arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
arr的维度： 2
元素的个数： 6
元素的数据类型： int32
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [9]:
#基础的创建方法
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [10]:
#基础的创建方法,与上面划等号
list1 = [1,2,3]
arr = np.array(list1,dtype=np.float64) #可以强制转化元素类型
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [11]:
# copu
arr1 = np.copy(arr) #内容一样，但是是两个数组
print(arr1)

[1. 2. 3.]


In [12]:
# 预定义形状
# 全0 全1 未初始化
# 全0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [13]:
arr = np.zeros((2,3),dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [14]:
# 全1
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 未初始化，值不确定
arr = np.empty((4,3))
print(arr)

[[1.46012765e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.04082753e-047]
 [6.81639530e-091 3.53727220e-057 3.55152631e-062]
 [5.99058616e-066 3.99910963e+252 9.51926506e+169]]


In [16]:
# full
arr = np.full((2,3),2025)
print(arr)

[[2025 2025 2025]
 [2025 2025 2025]]


In [17]:
arr1 = np.zeros_like(arr) #会覆盖之前的2025
print(arr1)

[[0 0 0]
 [0 0 0]]


In [18]:
# 等差数列 2,4,6,8
arr = np.arange(1,10,1) #start,end,step,[ , )
print(arr)

[1 2 3 4 5 6 7 8 9]


In [19]:
# 等间隔数列
arr = np.linspace(1,10,5) #start,end,几份
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
arr = np.linspace(0,100,5,dtype=int) #start,end,几份
print(arr)

[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2)  #start,end,几份，以2为底
print(arr)   #2的0次方是1，2次方是4，4次方是16

[ 1.  4. 16.]


In [22]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3,dtype = int)  #3是形状
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
arr = np.eye(3,4,dtype = int)  #3,4是形状
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [24]:
# 对角矩阵:主对角线上的数字非0，其余为0
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [25]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）   均匀分布指的是概率相等
arr = np.random.rand(2,3)
print(arr)

[[0.96630799 0.43327253 0.72526207]
 [0.71442137 0.86996713 0.18371977]]


In [26]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3)) #3 到6
print(arr)

[[4.31426781 3.40709854 5.11994955]
 [3.02552815 3.18937189 3.00367048]]


In [27]:
# 生成指定范围区间的随机整数
arr = np.random.randint(2,30,(2,3)) #2到30，(  ]
print(arr)

[[29 15  2]
 [13 11 14]]


In [28]:
#生成随机数列 （正态分布） 
arr = np.random.randn(2,3) 
print(arr)

[[-2.17554903  0.85913648 -1.3181008 ]
 [ 0.84197288  1.07184078 -0.50168009]]


## 4 索引与切片

In [29]:
arr = np.random.randint(1,100,20)
print(arr)

[11 52 48 57  1 14 38 53 86 20 95 65 54  6 40 57 74 82 76  8]


In [30]:
print(arr[:]) #获取全部数据
print(arr[2:5]) #获取2到4的元素  [  )
print(arr[(arr>10) & (arr<60)]) #布尔索引，就是条件
print(arr[slice(2,5)])  # start,end,step  [    )

[11 52 48 57  1 14 38 53 86 20 95 65 54  6 40 57 74 82 76  8]
[48 57  1]
[11 52 48 57 14 38 53 20 54 40 57]
[48 57  1]


In [31]:
# 二维数组索引和切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[ 9 17 27 70 31 86 34 80]
 [57 26 33 85 73 19 54 90]
 [35  3 69 23 11 22 78 70]
 [31 38 20 32 35 58 81 73]]


In [32]:
print(arr[1,3])   # 索引
print(arr[ 1,2:5])  # 1指的是第“1”行    2；5是2到5
print(arr[arr>50])  # 会变成一维数组
print(arr[2][ arr[2] > 50])    #第“2”行 大于50

85
[33 85 73]
[70 86 80 57 85 73 54 90 69 78 70 58 81 73]
[69 78 70]


## 5 ndarray运算

In [33]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)    #包括其余  - * / **

[5 7 9]


In [34]:
c = [1,2,3]
d = [4,5,6]
print(c+d)   #这里是列表和数组的差距,列表只能拼接

[1, 2, 3, 4, 5, 6]


In [35]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3) # 依旧演示,各个位置都加3   其余算数同理

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# 广播机制: 1 获取形状 2 是否可以广播         例如 1 * 2 和 1*3不行
# 同意维度 : 相同
a = np.array([1,2,3])  #  1 * 3
b = np.array([[4],[5],[6]]) # 3 * 1
print(a+b)
#      a
#    1 2 3
#    1 2 3
#    1 2 3
#      b
#    4 4 4
#    5 5 5
#    6 6 6 

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a*b)  # 这是数组的乘
print(a @ b) #这是矩阵的乘

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 二 numpy中的数学函数

## 1.基本数学函数

In [38]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [39]:
# 计算指数  默认以e为底  e^x
print(np.exp(1))
print(np.exp(0))

2.718281828459045
1.0


In [40]:
# 计算自然对数   默认e为底 ln x
print(np.log(2.71))

0.9969486348916096


In [41]:
# 计算正弦余弦
print(np.sin(np.pi/2))
print(np.cos(0))

1.0
1.0


In [42]:
# 计算绝对值
arr = np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [43]:
# 计算a的b次幂
print(np.power(arr,3))

[ -1   1   8 -27]


In [44]:
# 四舍五入
print(np.round([3.2,4.5,8.51,9.6]))

[ 3.  4.  9. 10.]


In [45]:
# 向上取整和向下取整
arr = np.array([3.2,4.5,8.51,9.6])
print(np.ceil(arr))
print(np.floor(arr))

[ 4.  5.  9. 10.]
[3. 4. 8. 9.]


In [46]:
# 检测缺失值NAN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

# 2.统计函数 
  求和，计算平均值，计算中位数，标准差，方差，查找最大值，最小值
  计算分为数，累计和，累计差

In [47]:
arr = np.random.randint(1,20,8)
print(arr)

[15 13 12  2 10  5  7  3]


In [48]:
#求和
print(np.sum([1,2,3]))

6


In [49]:
# 平均值
print(np.mean((arr)))

8.375


In [50]:
# 中位数
print(np.median([1,2,3,4]))
print(np.median([1,2,4]))

2.5
2.0


In [51]:
# 计算标准差，方差  
print(np.var([1,2,3]))
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [52]:
# 最大值最小值

In [53]:
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[15 13 12  2 10  5  7  3]
15 0
2 3


In [54]:
# 分为数，中位数  
print(np.median([1,2,3]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,50))  # 就是百分之五十

2.0
[44 47 64 67]
55.5
55.5


In [55]:
# 累计和，累计积
arr = np.array([1,2,3])
print(np.sum(arr)) # 求和
print(np.cumsum(arr)) # 累计和
print(np.cumprod(arr)) # 累计积

6
[1 3 6]
[1 2 6]


## 比较函数

In [63]:
# 是否大于
print(np.greater([3,4,5,6,7],4))
# 是否小于
print(np.less([3,4,5,6,7,],4))
# 是否等于
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[3,4,4]))  # 注意形状要相同，不然报错 

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[ True  True False]


In [65]:
print(np.logical_and([1,0],[1,1]))    #逻辑与
print(np.logical_or([0,0],[1,1]))     #逻辑或
print(np.logical_not([1,0]))          #相反 

[ True False]
[ True  True]
[False  True]


In [66]:
# 检查元素是否至少有一个元素为True
print(np.any([0,0,0,0,0,1]))
print(np.all([1,1,1,1,0]))

True
False


In [72]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件的))
arr = np.array([1,2,3,4,5])
print(np.where(arr>3,arr,0))

[0 0 0 4 5]


In [75]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,1,0))  #用来分类

[1 1 0 0 0]


In [88]:
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>=60,"及格","不及格"))

[59 82 81 60 73 85 61 78 84 50 50 86 55 88 90 67 65 54 91 92]
['不及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '不及格' '不及格' '及格' '不及格' '及格'
 '及格' '及格' '及格' '不及格' '及格' '及格']


In [91]:
# 嵌套用法
print(np.where(score<60,"不及格",np.where(score<80,"良","优秀")))

['不及格' '优秀' '优秀' '良' '良' '优秀' '良' '良' '优秀' '不及格' '不及格' '优秀' '不及格' '优秀'
 '优秀' '良' '良' '不及格' '优秀' '优秀']


In [94]:
# np.select (条件，返回的结果)
print(np.select([score>80,(score>=60) & (score<=80) , score<60],['优秀','良好','不及格'],default = '未知'))

['不及格' '优秀' '优秀' '良好' '良好' '优秀' '良好' '良好' '优秀' '不及格' '不及格' '优秀' '不及格' '优秀'
 '优秀' '良好' '良好' '不及格' '优秀' '优秀']


In [104]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
# arr.sort()     会直接改变数组的顺序
# print(arr) 
print(np.sort(arr))   # 不会污染原始数组
print(np.argsort(arr))  # 索引

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]


In [106]:
# 去重函数
print(np.unique(arr))   #去重的同时会重新排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [108]:
# 数组拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)   
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [111]:
# 数组分割
print(np.split(arr,4))  # 等分
print(np.split(arr,[6,12,18]))   # 切割未知的索引值

[array([45, 48, 65, 68, 68]), array([10, 84, 22, 37, 88]), array([71, 89, 89, 13, 59]), array([66, 40, 88, 47, 89])]
[array([45, 48, 65, 68, 68, 10]), array([84, 22, 37, 88, 71, 89]), array([89, 13, 59, 66, 40, 88]), array([47, 89])]


In [113]:
# 调整数组形状
print(np.reshape(arr,[4,5]))    # 切割成四行五列

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
